name: test_build
on: [push]
jobs:
  check_installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y liblapack-dev libblas-dev libopenmpi-dev
      - name: get PDAF
        run: |
            wget -O PDAF-D_V1.16.tar.gz "${{ env.PDAF_LINK }}"
            tar -zxvf PDAF-D_V1.16.tar.gz
        env:
          PDAF_LINK: ${{ secrets.PDAF116_LINK }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2

      - name: install pyPDAF
        run: |
          $CONDA/bin/conda install python
          pip install -v -e .
